### ISSUE TITLE
[BUG] Not able to delete Hybrid AKS clusters. Only node pools gets deleted after that the resource bridge is broken.

### ISSUE THREAD

**Issue by The-TeQnician** [Azure/aks-hybrid#342]
**Describe the bug**
I am not able to delete Hybrid AKS clusters from Azure Stack HCI. If i want to delete a successfully deployed cluster via the portal it only deletes the nodepool workers and then stops. Load balancer and control plane stay behind and after 15 to 30 minutes the delete job fails with an undefined error. After that the resource bridge stops working and new deployments also fail. 

**To Reproduce**
1. From the portal go to the Hybrid AKS cluster
2. Click on delete
3. Delete jobs runs and nodepools get deleted.
4. Then the delete jobs keeps on running and fails

**Expected behavior**
When i delete an hybrid AKS cluster from the portal i expect it to work. Node pools, Load Balancer and Management pane deleted from HCI cluster and objects removed from the portal.

**Screenshots**
![Inkedportal1](https://github.com/Azure/aks-hybrid/assets/17824200/877c90be-135f-4691-92d3-f85a145bd325)
![Inkedfailovercluster](https://github.com/Azure/aks-hybrid/assets/17824200/1e49a57b-384f-47ae-ac31-473c52729756)
![image](https://github.com/Azure/aks-hybrid/assets/17824200/4fa0241b-e49f-4168-80fe-eb33ad6c0e23)

**Environment (please complete the following information):**
- OS: Azure Stack HCI OS 22H2
- Browser: Edge
- Version: 112.0.1722.64 
- AKS-HCI Version: Resource bridge version 1.0.11
- Kubernetes Version: (v1.22.11)
- AZ CLI Version:     "azure-cli": "2.46.0",
  "azure-cli-core": "2.46.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "arcappliance": "0.2.30",
    "azurestackhci": "0.2.6",
    "customlocation": "0.1.3",
    "hybridaks": "0.2.1",
    "k8s-extension": "1.4.0"
  }

**Additional context**
This environment is a 4 node cluster with Azure Stack HCI 22H2. Environments contains AKS Resource bridge, ARC VM Self Service and Hybrid AKS resource bridges. Even after several redploys of the resource bridge it keeps failing when deleting Hybrid AKS clusters.

**Comment by HariPrasadV** [comment]
@The-TeQnician we rolled out a fix for the delete issue. One of the resourceTypes: provisionedClusters/upgradeProfiles was under a feature flag and since your subscription was not registered for that feature flag, azure was not able to delete it, and in turn it was blocking the delete of the parent resource (provisionedClusters) as well. We have removed that feature flag and rolled out the change and you should be able to see it as a part of Microsoft.HybridContainerService RP in your subscription now (You can check `az provider show -n "Microsoft.HybridContainerService"` to see if it has `"resourceType": "provisionedClusters/upgradeProfiles"`) Can you please retry the delete and let us know how it goes?

**Comment by The-TeQnician** [comment]
Hi @HariPrasadV, i have been testing this and it seems to fixed the issue when the resource type is registered! Great thanks!!

**Comment by ELVI131** [comment]
hello all, i have problem with an aks arc I am not able to delete,t he status at the moment is is invalid as it is being provisioned with state: 'Deleting', for more info the infrastructure is azure stack hci (aks-hci)hci 23h2  was build with jumpstart hcibox, I have delete the role in the failover cluster part but not able to delete the aks arc that at the moment is :  Status: Offline  and  Current state: Failed, also                                               


The ConnectedCluster wrapper is stuck in provisioningState=Deleting.
Underlying ProvisionedCluster and node‑pool VMs are already removed.
All customer‑side delete attempts with forceDelete=true (API 2024‑07‑15‑preview)
return InvalidResourceOperation. No locks, no deny assignments, no
finalizers remain. 

Tried from azure cli also from azure portal 

Has anyone faced this problem?

THNX

**Comment by Elektronenvolt** [comment]
Hi @ELVI131 - follow these two troubleshooting guides:

If anything from the cluster still exists - check for PodDisruptionBudget resources: https://learn.microsoft.com/en-us/azure/aks/aksarc/delete-cluster-pdb?tabs=aks-on-azure-local

Otherwise this should work at Azure CLI: https://learn.microsoft.com/en-us/azure/aks/aksarc/deleted-cluster-visible

**Comment by ELVI131** [comment]
hello, thnx but i already tried these steps and they arent working

**Comment by Elektronenvolt** [comment]
In this case - time is for sure better invested into setting up the jumpstart box fresh instead for trying to fix it.

**Comment by ELVI131** [comment]
yep, same issue I try every command possible and even this :  https://learn.microsoft.com/en-us/azure/aks/aksarc/deleted-cluster-visible , but still remain, and the other issue with that is if you have a logical network bound you are not able to delete that.

**Comment by Elektronenvolt** [comment]
OK, in my case it looks like some VMs that failed provisioning in the failover cluster below are not deleted/ cleaned up. It's a follow up issue to something else. Running a support case for that. In your case - making the HCIBox fresh is still a good idea :-)
